### ISSUE TITLE
docker build and docker compose fails on step 15 of server

### ISSUE THREAD

**Issue by pitch2sell** [valasek/timesheet#9]
**Description**
 COPY ./server/timesheet-dataarch.yaml /timesheet.yaml 
returns error

Step 15/36 : COPY ./server/timesheet-dataarch.yaml /timesheet.yaml
COPY failed: stat /var/lib/docker/tmp/docker-builder060440867/server/timesheet-dataarch.yaml: no such file or directory

**To Reproduce**
Docker-Compose:
1. docker-compose -f "docker-compose.yml" up -d --build
2. gets to step 15/36 and then fails

Docker:
1. docker build --rm -f "Dockerfile" -t timesheet:latest .
2. gets to step 15/36 and then fails

**Expected behavior**
Expect the container to be created

**Docker info:**
 - OS: MacOS
 - Client: Docker Engine - Community 
 - Version: 18.09.2

**Additional context**

**Comment by valasek** [comment]
Hi @pitch2sell, thank you for reporting he issue.
Please change the line
`COPY ./server/timesheet-dataarch.yaml /timesheet.yaml`
to
`COPY ./server/timesheet-cloud.yaml /timesheet.yaml`

This is due to copying a private file of a commercial customer.
Did it solve your problem?
